apiVersion: v1
kind: Secret
metadata:
  name: ollama-dummy-key
  namespace: kagent
type: Opaque
stringData:
  OLLAMA_API_KEY: "ollama"
---
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: ollama-model-config
  namespace: kagent
  labels:
    app.kubernetes.io/name: podlikar
    app.kubernetes.io/part-of: kagent
spec:
  apiKeySecret: ollama-dummy-key
  apiKeySecretKey: OLLAMA_API_KEY
  model: llama3.2:latest
  provider: Ollama
  ollama:
    host: http://192.168.8.164:11434
